### ISSUE TITLE
rip

### ISSUE THREAD

**Issue by TewPingz** [CoOwner/LunarClientAPI#1]
nice code bro, except the package is still named net.mineaus, you might have forgot to refactor that when you were skidding it from my one LOLOL

**Comment by CoOwner** [comment]
In fact nothing was fixed. I published it since it was leaked by wmarl. No ownership has been claimed here.

**Comment by CoOwner** [comment]
If you’re talking about the commits it was a random shit that I put, nothing is edited regardless 🤷‍♂️

**Comment by TewPingz** [comment]
wmarl was given permission to release it by me and then the ownership of the repository was then moved to skeltalgit

**Comment by CoOwner** [comment]
That’s the thing, since it was released and this repository was privated I decided to release it as well. But as I have claimed, nothing is claimed that I’ve coded this or anything.

**Comment by CoOwner** [comment]
If you wish to discuss this further, add me on telegram. @CoOwner.

**Comment by TewPingz** [comment]
so was it you who went on mcm and called the code shit? or was that someone else

**Comment by CoOwner** [comment]
I’ve purchased the code, code was released by the permission of Sam and yours, I decided to re-release it

**Comment by TewPingz** [comment]
sorry about this trash talk, some guy went on blackspigot and called it shit, then someone sent me the screenshot of guy talking shit and he said this one was better, guessed it was him not you

**Comment by CoOwner** [comment]
My identities are: Dreamzy, CoOwner & David. But I accept your apology man, have a great rest of your day.

**Comment by pmpy** [comment]
lol
